import mongoose from 'mongoose';
import { QUESTION_DIFFICULTIES } from '../../config/constants.js';

/**
 * A diagnostic assessment for one student in one course. Questions are
 * generated by the LLM provider against the course's actual topics and
 * learning objectives, then validated with Zod before persistence.
 *
 * Answers embed the AI evaluation (correctness + generated feedback text):
 * the structured, authoritative outcome lives separately in learning_evidence
 * - this document is the generated-text side of that split.
 */
const diagnosticQuestionSchema = new mongoose.Schema(
  {
    topicId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
    },
    objectiveCode: { type: String, default: null, maxlength: 30 },
    prompt: { type: String, required: true, minlength: 8, maxlength: 1000 },
    difficulty: {
      type: String,
      enum: Object.values(QUESTION_DIFFICULTIES),
      required: true,
    },
    generatedBy: { type: String, required: true },
  },
  { _id: true },
);

const answerEvaluationSchema = new mongoose.Schema(
  {
    correctness: {
      type: String,
      enum: ['incorrect', 'partial', 'correct'],
      required: true,
    },
    // Derived deterministically in the service (correct=1, partial=0.5,
    // incorrect=0) - the LLM never outputs this number.
    score: { type: Number, required: true, min: 0, max: 1 },
    confidence: { type: Number, min: 0, max: 1, default: null },
    misconceptions: {
      type: [{ code: { type: String, default: null, maxlength: 60 }, description: String }],
      default: [],
    },
    // Generated feedback prose (kept out of learning_evidence by design).
    feedback: { type: String, required: true, maxlength: 2000 },
    model: { type: String, required: true },
    evaluatedAt: { type: Date, default: Date.now },
  },
  { _id: false },
);

const diagnosticAnswerSchema = new mongoose.Schema(
  {
    questionId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
    },
    responseMode: { type: String, enum: ['text', 'voice'], default: 'text' },
    responseText: { type: String, required: true, maxlength: 8000 },
    // Present for voice answers (transcription provider output).
    transcript: { type: String, default: null, maxlength: 8000 },
    transcriptModel: { type: String, default: null },
    evaluation: { type: answerEvaluationSchema, required: true },
    evidenceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'LearningEvidence',
      default: null,
    },
    answeredAt: { type: Date, default: Date.now },
  },
  { _id: false },
);

const diagnosticAssessmentSchema = new mongoose.Schema(
  {
    studentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    courseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Course',
      required: true,
    },
    institutionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Institution',
      default: null,
    },
    isPersonal: { type: Boolean, default: false },
    status: {
      type: String,
      enum: ['in_progress', 'completed', 'abandoned'],
      default: 'in_progress',
    },
    targetTopicIds: { type: [mongoose.Schema.Types.ObjectId], default: [] },
    questions: { type: [diagnosticQuestionSchema], default: [] },
    answers: { type: [diagnosticAnswerSchema], default: [] },
    startedAt: { type: Date, default: Date.now },
    completedAt: { type: Date, default: null },
  },
  {
    timestamps: true,
    versionKey: false,
  },
);

diagnosticAssessmentSchema.index({ studentId: 1, courseId: 1, createdAt: -1 });

const DiagnosticAssessment = mongoose.model('DiagnosticAssessment', diagnosticAssessmentSchema);

/** Maps a lean assessment to the public API shape (owner's own view). */
export function toPublicDiagnostic(assessment) {
  return {
    id: assessment._id.toString(),
    studentId: assessment.studentId.toString(),
    courseId: assessment.courseId.toString(),
    status: assessment.status,
    targetTopicIds: (assessment.targetTopicIds ?? []).map((id) => id.toString()),
    questions: (assessment.questions ?? []).map((question) => ({
      id: question._id.toString(),
      topicId: question.topicId.toString(),
      objectiveCode: question.objectiveCode ?? null,
      prompt: question.prompt,
      difficulty: question.difficulty,
      generatedBy: question.generatedBy,
    })),
    answers: (assessment.answers ?? []).map((answer) => ({
      questionId: answer.questionId.toString(),
      responseMode: answer.responseMode,
      responseText: answer.responseText,
      transcript: answer.transcript ?? null,
      evaluation: {
        correctness: answer.evaluation.correctness,
        score: answer.evaluation.score,
        confidence: answer.evaluation.confidence ?? null,
        misconceptions: answer.evaluation.misconceptions ?? [],
        feedback: answer.evaluation.feedback,
        model: answer.evaluation.model,
        evaluatedAt: answer.evaluation.evaluatedAt,
      },
      evidenceId: answer.evidenceId ? answer.evidenceId.toString() : null,
      answeredAt: answer.answeredAt,
    })),
    questionCount: (assessment.questions ?? []).length,
    answeredCount: (assessment.answers ?? []).length,
    startedAt: assessment.startedAt,
    completedAt: assessment.completedAt ?? null,
    createdAt: assessment.createdAt,
  };
}

export default DiagnosticAssessment;