import mongoose from 'mongoose';
import { QUESTION_DIFFICULTIES } from '../../config/constants.js';

/**
 * A practice session for one student on one course topic (flow steps 14-16).
 * Questions are generated by the LLM provider against the topic, then
 * validated with Zod before persistence. Same governance split as
 * diagnostics: answers embed the AI evaluation + generated feedback text,
 * while the structured authoritative outcome lives separately in
 * learning_evidence (sourceType: "practice") and feeds the deterministic
 * learner model.
 */
const practiceQuestionSchema = new mongoose.Schema(
  {
    prompt: { type: String, required: true, minlength: 8, maxlength: 1000 },
    difficulty: {
      type: String,
      enum: Object.values(QUESTION_DIFFICULTIES),
      required: true,
    },
    generatedBy: { type: String, required: true },
  },
  { _id: true },
);

const answerEvaluationSchema = new mongoose.Schema(
  {
    correctness: {
      type: String,
      enum: ['incorrect', 'partial', 'correct'],
      required: true,
    },
    // Derived deterministically in the service (correct=1, partial=0.5,
    // incorrect=0) - the LLM never outputs this number.
    score: { type: Number, required: true, min: 0, max: 1 },
    confidence: { type: Number, min: 0, max: 1, default: null },
    misconceptions: {
      type: [{ code: { type: String, default: null, maxlength: 60 }, description: String }],
      default: [],
    },
    // Generated feedback prose (kept out of learning_evidence by design).
    feedback: { type: String, required: true, maxlength: 2000 },
    model: { type: String, required: true },
    evaluatedAt: { type: Date, default: Date.now },
  },
  { _id: false },
);

const practiceAnswerSchema = new mongoose.Schema(
  {
    questionId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
    },
    responseText: { type: String, required: true, maxlength: 8000 },
    evaluation: { type: answerEvaluationSchema, required: true },
    evidenceId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'LearningEvidence',
      default: null,
    },
    answeredAt: { type: Date, default: Date.now },
  },
  { _id: false },
);

const practiceSessionSchema = new mongoose.Schema(
  {
    studentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    courseId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Course',
      required: true,
    },
    topicId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
    },
    institutionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Institution',
      default: null,
    },
    isPersonal: { type: Boolean, default: false },
    status: {
      type: String,
      enum: ['in_progress', 'completed', 'abandoned'],
      default: 'in_progress',
    },
    questions: { type: [practiceQuestionSchema], default: [] },
    answers: { type: [practiceAnswerSchema], default: [] },
    startedAt: { type: Date, default: Date.now },
    completedAt: { type: Date, default: null },
  },
  {
    timestamps: true,
    versionKey: false,
  },
);

practiceSessionSchema.index({ studentId: 1, courseId: 1, createdAt: -1 });

const PracticeSession = mongoose.model('PracticeSession', practiceSessionSchema);

/** Maps a lean practice session to the public API shape (owner's own view). */
export function toPublicPracticeSession(session) {
  return {
    id: session._id.toString(),
    studentId: session.studentId.toString(),
    courseId: session.courseId.toString(),
    topicId: session.topicId.toString(),
    status: session.status,
    questions: (session.questions ?? []).map((question) => ({
      id: question._id.toString(),
      prompt: question.prompt,
      difficulty: question.difficulty,
      generatedBy: question.generatedBy,
    })),
    answers: (session.answers ?? []).map((answer) => ({
      questionId: answer.questionId.toString(),
      responseText: answer.responseText,
      evaluation: {
        correctness: answer.evaluation.correctness,
        score: answer.evaluation.score,
        confidence: answer.evaluation.confidence ?? null,
        misconceptions: answer.evaluation.misconceptions ?? [],
        feedback: answer.evaluation.feedback,
        model: answer.evaluation.model,
        evaluatedAt: answer.evaluation.evaluatedAt,
      },
      evidenceId: answer.evidenceId ? answer.evidenceId.toString() : null,
      answeredAt: answer.answeredAt,
    })),
    questionCount: (session.questions ?? []).length,
    answeredCount: (session.answers ?? []).length,
    startedAt: session.startedAt,
    completedAt: session.completedAt ?? null,
    createdAt: session.createdAt,
  };
}

export default PracticeSession;